// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjjA7U8vQScqbBoVK8KIuRYwHbNlslJEs',
    appId: '1:76923257784:web:f1be970b853a10aa7e054d',
    messagingSenderId: '76923257784',
    projectId: 'saed-app-project',
    authDomain: 'saed-app-project.firebaseapp.com',
    storageBucket: 'saed-app-project.appspot.com',
    measurementId: 'G-F0115JQCCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQIjRwRQ0g9Rblpe4m7b5N1a4awy30fqU',
    appId: '1:76923257784:android:7f4d6160f753a54d7e054d',
    messagingSenderId: '76923257784',
    projectId: 'saed-app-project',
    storageBucket: 'saed-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL3Vni6lsnkAK3k8DZRllpqtYUGLV2mIs',
    appId: '1:76923257784:ios:5306e7b067b598a97e054d',
    messagingSenderId: '76923257784',
    projectId: 'saed-app-project',
    storageBucket: 'saed-app-project.appspot.com',
    iosBundleId: 'com.example.pillApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL3Vni6lsnkAK3k8DZRllpqtYUGLV2mIs',
    appId: '1:76923257784:ios:4f7846831cf63ad17e054d',
    messagingSenderId: '76923257784',
    projectId: 'saed-app-project',
    storageBucket: 'saed-app-project.appspot.com',
    iosBundleId: 'com.example.pillApp.RunnerTests',
  );
}
